### PR TITLE
docs: added git process to contributing.md

### PR DESCRIPTION
**Pull request by john-whiting**

### CODE REVIEW

**Review by IllustratedMan-code — COMMENTED** [review]
Any reason to use the "release" branches from gitflow instead of tags? Only reason I suggest tags is that it integrates with CI/CD and Github's releases a bit better. Otherwise, I am fully on board.

**Review by adediu25 — APPROVED** [review]
David makes a good point but sounds good to me

**Comment by john-whiting** [comment]
> Any reason to use the "release" branches from gitflow instead of tags? Only reason I suggest tags is that it integrates with CI/CD and Github's releases a bit better. Otherwise, I am fully on board.

Tags are used as well. Release branches are usually part of a release workflow. I.e., you change a version number in some file, create/generate the changelog, etc. Basically, a step-off from develop for a little bit to do some housework before merging into main. The merge commit into main is the one that gets tagged with the version number.

**Review by IllustratedMan-code — APPROVED** [review]
Ok. Makes sense

**Pull request merged**
